### ISSUE TITLE
🐛 Can't parse diagram with cyclic timer event 

### ISSUE THREAD

**Issue by roblen45** [process-engine/process_engine_core#240]
#### Describe your issue

If you try to deploy a diagram with cyclic timer event, the parser throws an error.

#### How can others reproduce the issue?

I created the branch 'feature/fix_cyclic_timer_start_event' with a new unit test:

'Parse process_engine_io_release.bpmn Diagram'

#### Possible solution

Allow this kind of StartEvent.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by roblen45** [comment]
https://github.com/5minds/dog-food-klub/issues/14

**Comment by ElRaptorus** [comment]
@roblen45 As we discussed earlier, this is intended behavior, since cyclic timers are not supported yet.

@robpal94 will loosen the restrictions on this a bit, so it becomes possible to deploy such diagrams, if at least one non-cyclic timer start event is present (keep an mind that this includes `SignalStartEvents`, `MessageStartEvents` and `TimerStartEvents` without a cyclic timer as well).

**Comment by ElRaptorus** [comment]
@roblen45 Also, please place such issues in the runtime as well, so we can refer to them in the change notes of the releases.
